### ISSUE TITLE
cannot pull image on macOS M1

### ISSUE THREAD

**Issue by Houssainatou** [green-code-initiative/ecoCode-common#12]
I try to run given commands to pull docker images on macOS M1 (arm), then I get this message:
```
Unable to find image 'ghcr.io/green-code-initiative/sonarqube-ecocode:latest' locally
latest: Pulling from green-code-initiative/sonarqube-ecocode
docker: no matching manifest for linux/arm64/v8 in the manifest list entries.
See 'docker run --help'.
```

Can we have docker image which works on this OS? 
Thanks

**Comment by dedece35** [comment]
Hi @Houssainatou;

thank you for your issue.
Indeed, only one people of core team has a M1 MacOS and we don't have tested this docker process on M1 or M2.
@jhertout, an idea ?

By another hand you can build your installation from scratch if you follow `INSTALL.md` file.
The docker command present in `README.md` is for people who wants to test our plugins without install all the technical stack (maybe it's your case).

We asking for people who could check it.

**Comment by Houssainatou** [comment]
> Hi @Houssainatou;
> 
> thank you for your issue. Indeed, only one people of core team has a M1 MacOS and we don't have tested this docker process on M1 or M2. @jhertout, an idea ?
> 
> By another hand you can build your installation from scratch if you follow `INSTALL.md` file. The docker command present in `README.md` is for people who wants to test our plugins without install all the technical stack (maybe it's your case).
> 
> We asking for people who could check it.

Hi @dedece35,
Thanks, for your response. I install it by following `Install.md` everything is OK with `Install.md`. Thanks
