### ISSUE TITLE
Check access and usage of all tools for 2023 hackathon

### ISSUE THREAD

**Issue by dedece35** [green-code-initiative/ecoCode-common#5]
with a new github account (creation of test account), check following : 
- access to repositories : `ecoCode-common`, `ecoCode-challenge`, `ecoCode`, `ecoCode-mobile` and `ecoCode-linter`
   - read access
   - PR creation access from personal fork
   - neither PR merge access, nor directly write access, nor branch creation access
- following starter-pack.md and install.md, check if all is ok to start development in local machine
- launch a real modification with a PR (ex : documentation modification) to check that process is OK

**Comment by jules-delecour-dav** [comment]
I've created this file => [https://github.com/green-code-initiative/ecoCode-challenge/pull/3/files](url) which is based on the procedure to start for the first time the project

**Comment by dedece35** [comment]
Hi @utarwyn, @jules-delecour-dav 
all was ok for challenge and the Jules's PR was already merged.
I close this issue.
