### ISSUE TITLE
Improve check_requirements tool for Windows

### ISSUE THREAD

**Issue by dedece35** [green-code-initiative/ecoCode-common#7]
Currently, `check_requirements.sh` tool for Unix and MacOS check installations and some versions required.
For Windows tool, installations are verified but versions are not. Only a message to check is displayed.

Improve this Windows tool to check also versions.

**Comment by d-casal** [comment]
Hi, I'd like to work on this issue. Can I take it up?

**Comment by dedece35** [comment]
Hi @d-casal,
yes ! no problem !

here is bash script for unix / MAC : https://github.com/green-code-initiative/ecoCode-common/blob/main/tools/check_requirements/check_requirements.sh
here is BAT script  for windows : https://github.com/green-code-initiative/ecoCode-common/blob/main/tools/check_requirements/check_requirements.bat

Feel free to improve them !

**Comment by d-casal** [comment]
Thank you @dedece35, I will get to work then. I am expecting to raise a pull request in the coming weeks, toward the the end of November

**Comment by d-casal** [comment]
Changes are progressing well. Aiming to raise a PR the week starting on the 27th of November.

**Comment by d-casal** [comment]
![check_require-capture-windows](https://github.com/green-code-initiative/ecoCode-common/assets/91036734/d24b3033-edfb-4e67-b5ed-afee3ef8e8e3)

**Comment by d-casal** [comment]
@dedece35 this is ready for review. Let me know if you have any feedback.

**Comment by dedece35** [comment]
@d-casal 
thank you for contribution !
great job !
